server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.135.34.35:3306/clark_database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: clark
    password: rootroot

  mail:
    host: smtp.qq.com
    username: 2868451714@qq.com
    password: cdmlsndkcqhrdhfb

  mvc:
    static-path-pattern: "/static/**"


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.clarklyy.website.domain.entity.User

management:
  endpoints:
    web:
      exposure:
        include: "*"

clark:
  jwt:
    secret: 12312414123123
    expire: 604800
    header: Authorization
